--- 
title: "Project1" 
output: 
  html_document: 
    keep_md: true 
---
Task 1
```{r, echo=TRUE}


stepsdata<-read.csv("activity.csv")
head(stepsdata)
```
Task 2
```{r}
library(dplyr)
library(magrittr)

daily<-stepsdata %>% 
    select(steps,date) %>% 
    group_by(date) %>%
    summarize(dsteps=sum(steps)) %>% 
    na.omit()
daily

hist(daily$dsteps,xlab="Daily Steps",main="Histogram of DSteps",breaks=25)
```

Task 3
```{r}
daily
mean(daily$dsteps)
median(daily$dsteps)
```


Task 4
```{r}
intervals<-stepsdata %>% 
    na.omit() %>% 
    select(steps,interval) %>% 
    group_by(interval) %>% 
    summarize(dsteps=mean(steps))
intervals
library(ggplot2)
ggplot(intervals,aes(x=interval,y=dsteps))+geom_line()
```

Task 5
```{r}
intervals[which(intervals$dsteps==max(intervals$dsteps)),]
```

Task 6
```{r}
missing<-sum(is.na(stepsdata))
missing
replacewithmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
meandata <- stepsdata%>% group_by(interval) %>% mutate(steps= replacewithmean(steps))
head(meandata)
```

Task 7
```{r}
full <- aggregate(meandata$steps, by=list(meandata$date), sum)

names(full)[1] ="date"
names(full)[2] ="totalsteps"
head(full,15)
hist(full$totalsteps)
```


Task 8
```{r}
oldmean <- mean(daily$dsteps, na.rm = TRUE)
newmean <- mean(full$totalsteps)

oldmedian <- median(daily$dsteps, na.rm = TRUE)
newmedian <- median(full$totalsteps)
```


Task 9
```{r}
meandata$date <- as.Date(meandata$date)
meandata$weekday <- weekdays(meandata$date)
meandata$weekend <- ifelse(meandata$weekday=="Saturday" | meandata$weekday=="Sunday", "Weekend", "Weekday" )

meandataweekendweekday <- aggregate(meandata$steps , by= list(meandata$weekend, meandata$interval), na.omit(mean))
names(meandataweekendweekday) <- c("weekend", "interval", "steps")

ggplot(meandataweekendweekday, aes(x=interval, y=steps, color=weekend)) + geom_line()+
    facet_grid(weekend ~.) + xlab("Interval") + ylab("Mean of Steps") +
    ggtitle("Comparison of Average Number of Steps in Each Interval")

```

```{r}
library(knitr)
knit2html("pa1_template.rmd")
```
